DB_NAME="${1-tw_db}"
DB_USER="${1-tw}"
PSQL="psql -X --set ON_ERROR_STOP=1 --set AUTOCOMMIT=off"

# createuser ${DB_USER} -P

cat <<EOF | ${PSQL} ${DB_NAME}
GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public
    TO ${DB_USER};

ALTER DEFAULT PRIVILEGES 
    IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};
EOF
